### ISSUE TITLE
Unknown options: '--wondershaperImage', 'theiacloud/theia-cloud-wondershaper:0.8.0.MS7'

### ISSUE THREAD

**Issue by kuldeeparora89** [eclipsesource/theia-cloud#132]
Hi,

I am facing below issue while deploying theiacloud in minikube :

```

Exception in thread "main" picocli.CommandLine$UnmatchedArgumentException: Unknown options: '--wondershaperImage', 'theiacloud/theia-cloud-wondershaper:0.8.0.MS7'
        at picocli.CommandLine$Interpreter.validateConstraints(CommandLine.java:13248)
        at picocli.CommandLine$Interpreter.parse(CommandLine.java:13200)
        at picocli.CommandLine$Interpreter.parse(CommandLine.java:13146)
        at picocli.CommandLine$Interpreter.parse(CommandLine.java:13047)
        at picocli.CommandLine.parseArgs(CommandLine.java:1478)
        at org.eclipse.theia.cloud.operator.Main.createArguments(Main.java:56)
        at org.eclipse.theia.cloud.operator.Main.runMain(Main.java:42)
        at org.eclipse.theia.cloud.operator.Main.main(Main.java:38)
```
On checking TheiaCloudArguments .java the argument wondershaperImage is missing . Please check

**Comment by kuldeeparora89** [comment]
Thanks @jfaltermeier . It worked.
