### ISSUE TITLE
Error while buiding new docker image of demo theia docker

### ISSUE THREAD

**Issue by haminlee** [eclipsesource/theia-cloud#142]
I was able to build new docker image from the folder "demo-theia-docker" since last January 10 on AKS.

However, it failed suddenly with this error after reinstalling at Februrary 6.

Here is the log messages from docker builder:

theia-blueprint-browser: + vscode.typescript-language-features@1.66.2: downloaded successfully 
theia-blueprint-browser: --- collecting extension dependencies ---
theia-blueprint-browser: --- resolving 3 extension dependencies ---
theia-blueprint-browser: - ms-vscode.node-debug2: already downloaded - skipping
theia-blueprint-browser: - vscjava.vscode-java-debug: already downloaded - skipping
theia-blueprint-browser: - redhat.java: already downloaded - skipping
theia-blueprint-browser: getaddrinfo EAI_AGAIN open-vsx.org
theia-blueprint-browser: getaddrinfo EAI_AGAIN open-vsx.org
theia-blueprint-browser: Error: Errors downloading some plugins. To make these errors non fatal, re-run with --ignore-errors
theia-blueprint-browser:     at downloadPlugins (/home/theia/theia-blueprint/node_modules/@theia/cli/lib/download-plugins.js:116:15)
theia-blueprint-browser:     at async Object.handler (/home/theia/theia-blueprint/node_modules/@theia/cli/lib/theia.js:313:13)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
theia-blueprint: + vscode.cpp@1.66.2: downloaded successfully 
theia-blueprint: + vscode.log@1.66.2: downloaded successfully 
Done in 385.63s.

 

 >  Lerna (powered by Nx)   Running target prepare for 5 projects failed

   Failed tasks:
   
   - theia-blueprint-browser:prepare

error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
The command '/bin/sh -c git clone https://github.com/eclipse-theia/theia-blueprint.git &&     cd theia-blueprint &&     git checkout jf/docker &&     yarn --pure-lockfile &&     yarn --production &&     yarn autoclean --init &&     echo *.ts >> .yarnclean &&     echo *.ts.map >> .yarnclean &&     echo *.spec.* >> .yarnclean &&     yarn autoclean --force &&     yarn cache clean' returned a non-zero code: 1

----------------------------------------

When the new line added with "yarn run env" in Dockerfile, it passed the error.
However, the pod on AKS failed with Crashloopbackoff error while showing 403 NOT THIS TIME, ACCESS FORBIDDEN!
[LOGOUT] in the browser.

----------------------------------------------

kubectl logs cbef7435-5afd-45e0-a3c1-946caa5440a0-deployment-paul-lee-n57j7r -n theiacloud
Defaulted container "oauth2-proxy" out of: oauth2-proxy, theia-cloud-demo
[2023/02/09 15:43:09] [validator.go:29] using authenticated emails file /emails/authenticated-emails-list
[2023/02/09 15:43:09] [watcher.go:40] watching '/emails/authenticated-emails-list' for updates
[2023/02/09 15:43:09] [provider.go:55] Performing OIDC Discovery...
[2023/02/09 15:43:09] [providers.go:145] Warning: Your provider supports PKCE methods ["plain" "S256"], but you have not enabled one with --code-challenge-method
[2023/02/09 15:43:09] [proxy.go:89] mapping path "/" => upstream "http://127.0.0.1:3000/"
[2023/02/09 15:43:09] [oauthproxy.go:162] OAuthProxy configured for Keycloak OIDC Client ID: theia-cloud
[2023/02/09 15:43:09] [templates.go:73] Could not load file /templates/robots.txt: stat /templates/robots.txt: no such file or directory, will use default template
[2023/02/09 15:43:09] [oauthproxy.go:168] Cookie settings: name:_oauth2_proxy secure(https):false httponly:true expiry:168h0m0s domains:ws.20.121.232.185.nip.io path:/ samesite: refresh:disabled
[2023/02/09 15:43:09] [oauthproxy.go:476] Skipping auth - Method:  | Path: /health.*
[2023/02/09 15:43:09] [oauthproxy.go:345] WARNING: GCP HealthChecks are now deprecated: Reconfigure apps to use the ping path for liveness and readiness checks, set the ping user agent to "GoogleHC/1.0" to preserve existing behaviour
[2023/02/09 15:43:40] [oauthproxy.go:959] No valid authentication in request. Initiating login.
10.224.0.4 - 75636e8984d8f05d709b31b08a3243e3 - - [2023/02/09 15:43:40] ws.20.121.232.185.nip.io GET - "/" HTTP/1.1 "Java/11.0.14.1" 302 483 0.000
[2023/02/09 15:43:41] [error_page.go:93] Error proxying to upstream server: dial tcp 127.0.0.1:3000: connect: connection refused
10.244.0.1 - fd81d0a1ecdb24a8bab28728877f5206 - paul.lee@nttdata.com [2023/02/09 15:43:41] ws.20.121.232.185.nip.io GET / "/" HTTP/1.1 "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/110.0.0.0 Safari/537.36" 502 2253 0.001

**Comment by jfaltermeier** [comment]
Hi, the Theia Demo is built from a branch hosted at Theia Blueprint. There were some recent changes to this branch, which we did not adapt to yet. I've restored the old branch on Theia Blueprint and pushed to changes to a different one. 
Also open-vsx.org sometimes rejects requests when a rate limit is hit. 

`Error proxying to upstream server: dial tcp 127.0.0.1:3000: connect: connection refused` looks like the Theia application did not start up. 
You can test your image locally by running `docker run --rm -p 3000:3000 your-image-name:tag` and browsing to `http://localhost:3000/`

So my suggestion would be rebuild against the restored branch and test this new image again.

**Comment by haminlee** [comment]
Thank you!

I could build new image without an error on last Friday and now I got the same error while building new image.
