### ISSUE TITLE
Not Starting Workspace with Timeout

### ISSUE THREAD

**Issue by haminlee** [eclipsesource/theia-cloud#147]
[The Similar Error as  https://github.com/eclipsesource/theia-cloud/issues/133  but New Error with timeout]

I experienced the timeout issue with error code 504 from loading a workspace after installing theia-cloud on AKS with the azure subscription from the company while there was no issue on AKS from my personal subscription.

For my case, the CORS issue has been solved after adding CORS configuration below in ingress services for service and workspace.

annotations:
acme.cert-manager.io/http01-edit-in-place: "true"
cert-manager.io/cluster-issuer: letsencrypt-prod
kubernetes.io/ingress.class: nginx
nginx.ingress.kubernetes.io/enable-cors: "true"
nginx.ingress.kubernetes.io/cors-allow-credentials: "true"
nginx.ingress.kubernetes.io/cors-allow-origin: "https://theia.cloud.xx.xx.xx.xx.nip.io/"
nginx.ingress.kubernetes.io/cors-allow-methods: "PUT, GET, POST, OPTIONS, DELETE"
nginx.ingress.kubernetes.io/cors-allow-headers: "Authorization,DNT,X-CustomHeader,X-LANG,Keep-Alive,User-Agent,X-Requested-With,If-Modified-Since,Cache-Control,Content-Type,X-Api-Key,X-Device-Id,Access-Control-Allow-Origin"

However, new timeout error with error 504 has been shown in the browser.

![image](https://user-images.githubusercontent.com/17012566/223569364-4aade383-4fc9-4ead-a014-96de6201281e.png)

From the log, it seems failed to launch the existing workspace :

2023-03-07 21:42:36,982 INFO [io.quarkus] (main) service 0.7.0-SNAPSHOT on JVM (powered by Quarkus 2.12.0.Final) started in 3.802s. Listening on: http://0.0.0.0:8081/
2023-03-07 21:42:36,983 INFO [io.quarkus] (main) Profile prod activated.
2023-03-07 21:42:36,983 INFO [io.quarkus] (main) Installed features: [cdi, keycloak-authorization, oidc, resteasy-reactive, resteasy-reactive-jackson, security, smallrye-context-propagation, smallrye-openapi, vertx]
2023-03-07 21:50:56,821 WARN [io.fab.kub.cli.int.VersionUsageUtils] (executor-thread-0) The client is using resource type 'workspaces' with unstable version 'v1beta'
2023-03-07 21:50:57,004 INFO [org.ecl.the.clo.ser.RootResource] (executor-thread-0) [dc472b63-3d1a-4e03-a1c2-d25c87c9643d] Launching existing workspace session LaunchRequest [user=[paul.lee@xxxx.com](mailto:paul.lee@xxxx.com), appDefinition=theia-cloud-demo, workspaceName=[ws-asdfghjkl-theia-cloud-demo-paul.lee@xxxx.com](mailto:ws-asdfghjkl-theia-cloud-demo-paul.lee@xxxx.com), label=null, ephemeral=false, appId=asdfghjkl, kind=launchRequest, timeout=3]
2023-03-07 21:50:57,008 WARN [io.fab.kub.cli.int.VersionUsageUtils] (executor-thread-0) The client is using resource type 'sessions' with unstable version 'v2beta'
2023-03-07 21:51:55,656 INFO [org.ecl.the.clo.ser.RootResource] (executor-thread-1) [559ff86a-ac00-48f4-9e60-c40b4020985a] Launching existing workspace session LaunchRequest [user=[paul.lee@xxxx.com](mailto:paul.lee@xxxx.com), appDefinition=theia-cloud-demo, workspaceName=[ws-asdfghjkl-theia-cloud-demo-paul.lee@xxxx.com](mailto:ws-asdfghjkl-theia-cloud-demo-paul.lee@xxxx.com), label=null, ephemeral=false, appId=asdfghjkl, kind=launchRequest, timeout=3]
2023-03-07 21:52:55,769 INFO [org.ecl.the.clo.ser.RootResource] (executor-thread-2) [643cb12c-75c2-411b-b707-558b5320f099] Launching existing workspace session LaunchRequest [user=[paul.lee@xxxx.com](mailto:paul.lee@xxxx.com), appDefinition=theia-cloud-demo, workspaceName=[ws-asdfghjkl-theia-cloud-demo-paul.lee@xxxx.com](mailto:ws-asdfghjkl-theia-cloud-demo-paul.lee@xxxx.com), label=null, ephemeral=false, appId=asdfghjkl, kind=launchRequest, timeout=3]
2023-03-07 21:53:55,903 INFO [org.ecl.the.clo.ser.RootResource] (executor-thread-3) [06a353e4-cb96-433b-93c8-cc7c8082799e] Launching existing workspace session LaunchRequest [user=[paul.lee@xxxx.com](mailto:paul.lee@xxxx.com), appDefinition=theia-cloud-demo, workspaceName=[ws-asdfghjkl-theia-cloud-demo-paul.lee@xxxx.com](mailto:ws-asdfghjkl-theia-cloud-demo-paul.lee@xxxx.com), label=null, ephemeral=false, appId=asdfghjkl, kind=launchRequest, timeout=3]
21:53:57.085 [executor-thread-0] ERROR org.eclipse.theia.cloud.common.k8s.client.CustomResourceClient - [dc472b63-3d1a-4e03-a1c2-d25c87c9643d] Timeout while waiting for URL for _ws-asdfghjkl-theia-cloud-demo-paul-lee-**-com-session_
java.lang.InterruptedException: Timeout reached. Interrupt Watch.
at org.eclipse.theia.cloud.common.k8s.client.ResourceClient.watchUntil(ResourceClient.java:88) ~[service-0.7.0-SNAPSHOT-runner.jar:0.7.0-SNAPSHOT]
at org.eclipse.theia.cloud.common.k8s.client.DefaultSessionResourceClient.launch(DefaultSessionResourceClient.java:69) [service-0.7.0-SNAPSHOT-runner.jar:0.7.0-SNAPSHOT]
at org.eclipse.theia.cloud.common.k8s.client.SessionResourceClient.launch(SessionResourceClient.java:28) [service-0.7.0-SNAPSHOT-runner.jar:0.7.0-SNAPSHOT]
at org.eclipse.theia.cloud.service.K8sUtil.launchSession(K8sUtil.java:72) [service-0.7.0-SNAPSHOT-runner.jar:0.7.0-SNAPSHOT]
at org.eclipse.theia.cloud.service.K8sUtil.launchWorkspaceSession(K8sUtil.java:68) [service-0.7.0-SNAPSHOT-runner.jar:0.7.0-SNAPSHOT]
at org.eclipse.theia.cloud.service.RootResource.launch(RootResource.java:60) [service-0.7.0-SNAPSHOT-runner.jar:0.7.0-SNAPSHOT]
at org.eclipse.theia.cloud.service.RootResource_Subclass.launch$$superforward1(Unknown Source) [service-0.7.0-SNAPSHOT-runner.jar:0.7.0-SNAPSHOT]
at org.eclipse.theia.cloud.service.RootResource_Subclass$$function$$3.apply(Unknown Source) [service-0.7.0-SNAPSHOT-runner.jar:0.7.0-SNAPSHOT]
at io.quarkus.arc.impl.AroundInvokeInvocationContext.proceed(AroundInvokeInvocationContext.java:53) [service-0.7.0-SNAPSHOT-runner.jar:0.7.0-SNAPSHOT]
at io.quarkus.security.runtime.interceptor.SecurityHandler.handle(SecurityHandler.java:47) [service-0.7.0-SNAPSHOT-runner.jar:0.7.0-SNAPSHOT]
at io.quarkus.security.runtime.interceptor.AuthenticatedInterceptor.intercept(AuthenticatedInterceptor.java:29) [service-0.7.0-SNAPSHOT-runner.jar:0.7.0-SNAPSHOT]

From the log, the existing workspace is "ws-asdfghjkl-theia-cloud-demo-paul-lee--com-session" but I found that the actual workspace is named as app=ws-asdfghjkl-theia-cloud-demo-paul-lee--com-session**-2fb**.

![image](https://user-images.githubusercontent.com/17012566/223569281-2499c56c-459f-40eb-9bfb-22d73388d298.png)

the actual name has been copied and pasted here : app:ws-asdfghjkl-theia-cloud-demo-paul-lee-*-com-session-2fb

Could this unmatched workspace name be the cause of the error?

Thanks,

**Comment by lucas-koehler** [comment]
Hi @haminlee ,
it looks like your screenshot shows the **deployment** resource of the launched session. The label you see there, i.e. `app=ws-asdfghjkl-theia-cloud-demo-paul-lee-xxxxx-com-session-2fb` does not need to be the same as the session name.
This only needs to match the label of the launched pod (linked at the bottom of your screenshot).

You seem to have looked at the service logs. I suggest starting another workspace and then also check the operator logs. It might be that an error occurs there which prevents it from writing back the session URL and thus, the service timing out.

**Comment by lucas-koehler** [comment]
Hi @haminlee ,
it seems indeed suspicious that the name of the session pod contains the additional `a` in the beginning of its name.
There are now multiple places where the mismatch could be happening.
The continuing returnal of a 503 response code on the session pod url (i.e. ` ws.20.120.51.130.nip.io/76a8d62f-d47b-4282-afdf-5114bad87fab/` in your logs) indicates that an entry for the URL is present in the ingress but it cannot find the associated service or the service cannot find the session pod.
As these are all matched by names, the additional `a` in the session pod's name could cause such a problem.

To check for this, you can have a look at - and gladly paste the outputs here - the following resources after starting another session:

- Get the pods name
- Get the service associated with the pod. The service's name also starts with the uuid followed by `-service`.
  - The selector in the service should be the same as the selector in the deployment (like shown in your screenshot)
- Check the ingress. If you use the default name, it's named `theia-cloud-demo-ws-ingress`. It should have a `rule` pointing to the service mentioned before. The name must match the name of the service object. For instance, if the service object's name starts with the additonal "a" but this "a" is not present in the service name reference in the ingress object, this explains why the session pod can never be found on the URL.

Unfortunately, I have not seen this behavior before. Has one of you @jfaltermeier , @sgraband ?

**Comment by haminlee** [comment]
Hi @lucas-koeheler,

Thanks for your answers.

I got outputs from new workspace.
I couldn't reproduce every time the case with no "a" on URL. It happened once again but could get the right outputs.
I pasted all outputs to find why the ws is not available from operator's log . 
   _ws.20.120.51.130.nip.io/a4140cf8-b66e-4610-88ce-8d5a47d773fa/ is NOT available yet._

**- list of pods, services and other components.**

NAMESPACE       NAME                                                                  READY   STATUS    RESTARTS       AGE
cert-manager    pod/cert-manager-7b45d477c8-f5hj7                                     1/1     Running   0              3h9m
cert-manager    pod/cert-manager-cainjector-86f7f4749-8jlws                           1/1     Running   0              3h9m
cert-manager    pod/cert-manager-webhook-66c85f8577-mmxkj                             1/1     Running   0              3h9m
ingress-nginx   pod/ingress-nginx-controller-598d7c8b88-nxhf9                         1/1     Running   0              3h9m
ingress-nginx   pod/ingress-nginx-controller-598d7c8b88-tnx22                         1/1     Running   0              3h9m
keycloak        pod/keycloak-0                                                        1/1     Running   0              3h9m
keycloak        pod/keycloak-postgresql-0                                             1/1     Running   0              3h9m
kube-system     pod/azure-ip-masq-agent-8v7sd                                         1/1     Running   0              3h10m
kube-system     pod/cloud-node-manager-7r29n                                          1/1     Running   0              3h10m
kube-system     pod/coredns-59b6bf8b4f-bsh28                                          1/1     Running   0              3h9m
kube-system     pod/coredns-59b6bf8b4f-ldp99                                          1/1     Running   0              3h9m
kube-system     pod/coredns-autoscaler-5655d66f64-blb22                               1/1     Running   0              3h9m
kube-system     pod/csi-azuredisk-node-4pmnf                                          3/3     Running   0              3h10m
kube-system     pod/csi-azurefile-node-vj969                                          3/3     Running   0              3h10m
kube-system     pod/konnectivity-agent-78ffdd9778-6j86s                               1/1     Running   0              3h9m
kube-system     pod/konnectivity-agent-78ffdd9778-ks6st                               1/1     Running   0              3h9m
kube-system     pod/kube-proxy-cjtx6                                                  1/1     Running   0              3h10m
kube-system     pod/metrics-server-7dd74d8758-6d4vr                                   2/2     Running   0              3h9m
kube-system     pod/metrics-server-7dd74d8758-8wxgr                                   2/2     Running   0              3h9m
theiacloud      pod/a4140cf8-b66e-4610-88ce-8d5a47d773fa-deployment-paul-lee-nvknxb   2/2     Running   0              4m59s
theiacloud      pod/a5b682c08-ad6e-4cb7-b03c-1b4357b1f070-deployment-rubin-leewtcwb   2/2     Running   3 (3h5m ago)   3h9m
theiacloud      pod/landing-page-deployment-798cffd84f-6g9c8                          1/1     Running   0              3h9m
theiacloud      pod/operator-deployment-f97cd879-997nc                                1/1     Running   1 (157m ago)   3h9m
theiacloud      pod/service-deployment-548c87bbbd-b94ms                               1/1     Running   0              3h9m

NAMESPACE       NAME                                                                     TYPE           CLUSTER-IP     EXTERNAL-IP     PORT(S)                      AGE
cert-manager    service/cert-manager                                                     ClusterIP      10.0.237.61    <none>          9402/TCP                     4d
cert-manager    service/cert-manager-webhook                                             ClusterIP      10.0.4.181     <none>          443/TCP                      4d
default         service/kubernetes                                                       ClusterIP      10.0.0.1       <none>          443/TCP                      4d11h
ingress-nginx   service/ingress-nginx-controller                                         LoadBalancer   10.0.175.107   20.120.51.XXX.  80:31665/TCP,443:32363/TCP   3d22h
ingress-nginx   service/ingress-nginx-controller-admission                               ClusterIP      10.0.211.228   <none>          443/TCP                      3d22h
keycloak        service/keycloak-headless                                                ClusterIP      None           <none>          80/TCP                       3d22h
keycloak        service/keycloak-http                                                    ClusterIP      10.0.54.123    <none>          80/TCP,8443/TCP,9990/TCP     3d22h
keycloak        service/keycloak-postgresql                                              ClusterIP      10.0.132.255   <none>          5432/TCP                     3d22h
keycloak        service/keycloak-postgresql-headless                                     ClusterIP      None           <none>          5432/TCP                     3d22h
kube-system     service/kube-dns                                                         ClusterIP      10.0.0.10      <none>          53/UDP,53/TCP                4d11h
kube-system     service/metrics-server                                                   ClusterIP      10.0.97.1      <none>          443/TCP                      4d11h
theiacloud      service/a4140cf8-b66e-4610-88ce-8d5a47d773fa-service-paul-lee-nXXXXXaz   ClusterIP      10.0.26.239    <none>          3000/TCP                     5m
theiacloud      service/a5b682c08-ad6e-4cb7-b03c-1b4357b1f070-service-rubin-lee-gmailz   ClusterIP      10.0.248.33    <none>          3000/TCP                     4h46m
theiacloud      service/landing-page-service                                             ClusterIP      10.0.71.236    <none>          80/TCP                       7h16m
theiacloud      service/service-service                                                  ClusterIP      10.0.254.228   <none>          8081/TCP                     7h16m

NAMESPACE     NAME                                        DESIRED   CURRENT   READY   UP-TO-DATE   AVAILABLE   NODE SELECTOR   AGE
kube-system   daemonset.apps/azure-ip-masq-agent          1         1         1       1            1           <none>          4d11h
kube-system   daemonset.apps/cloud-node-manager           1         1         1       1            1           <none>          4d11h
kube-system   daemonset.apps/cloud-node-manager-windows   0         0         0       0            0           <none>          4d11h
kube-system   daemonset.apps/csi-azuredisk-node           1         1         1       1            1           <none>          4d11h
kube-system   daemonset.apps/csi-azuredisk-node-win       0         0         0       0            0           <none>          4d11h
kube-system   daemonset.apps/csi-azurefile-node           1         1         1       1            1           <none>          4d11h
kube-system   daemonset.apps/csi-azurefile-node-win       0         0         0       0            0           <none>          4d11h
kube-system   daemonset.apps/kube-proxy                   1         1         1       1            1           <none>          4d11h

NAMESPACE       NAME                                                                             READY   UP-TO-DATE   AVAILABLE   AGE
cert-manager    deployment.apps/cert-manager                                                     1/1     1            1           4d
cert-manager    deployment.apps/cert-manager-cainjector                                          1/1     1            1           4d
cert-manager    deployment.apps/cert-manager-webhook                                             1/1     1            1           4d
ingress-nginx   deployment.apps/ingress-nginx-controller                                         2/2     2            2           3d22h
kube-system     deployment.apps/coredns                                                          2/2     2            2           4d11h
kube-system     deployment.apps/coredns-autoscaler                                               1/1     1            1           4d11h
kube-system     deployment.apps/konnectivity-agent                                               2/2     2            2           4d11h
kube-system     deployment.apps/metrics-server                                                   2/2     2            2           4d11h
theiacloud      deployment.apps/a4140cf8-b66e-4610-88ce-8d5a47d773fa-deployment-paul-lee-nXXXX   1/1     1            1           4m59s
theiacloud      deployment.apps/a5b682c08-ad6e-4cb7-b03c-1b4357b1f070-deployment-rubin-lee-gma   1/1     1            1           4h46m
theiacloud      deployment.apps/landing-page-deployment                                          1/1     1            1           7h16m
theiacloud      deployment.apps/operator-deployment                                              1/1     1            1           7h16m
theiacloud      deployment.apps/service-deployment                                               1/1     1            1           7h16m

NAMESPACE       NAME                                                                                        DESIRED   CURRENT   READY   AGE
cert-manager    replicaset.apps/cert-manager-7b45d477c8                                                     1         1         1       4d
cert-manager    replicaset.apps/cert-manager-cainjector-86f7f4749                                           1         1         1       4d
cert-manager    replicaset.apps/cert-manager-webhook-66c85f8577                                             1         1         1       4d
ingress-nginx   replicaset.apps/ingress-nginx-controller-598d7c8b88                                         2         2         2       3d22h
kube-system     replicaset.apps/coredns-59b6bf8b4f                                                          2         2         2       4d11h
kube-system     replicaset.apps/coredns-autoscaler-5655d66f64                                               1         1         1       4d11h
kube-system     replicaset.apps/konnectivity-agent-775564c98f                                               0         0         0       4d11h
kube-system     replicaset.apps/konnectivity-agent-78ffdd9778                                               2         2         2       4d10h
kube-system     replicaset.apps/metrics-server-58df99c858                                                   0         0         0       4d11h
kube-system     replicaset.apps/metrics-server-7dd74d8758                                                   2         2         2       4d10h
kube-system     replicaset.apps/metrics-server-8655f897d8                                                   0         0         0       4d11h
theiacloud      replicaset.apps/a4140cf8-b66e-4610-88ce-8d5a47d773fa-deployment-paul-lee-nXXXX-55f675547b   1         1         1       4m59s
theiacloud      replicaset.apps/a5b682c08-ad6e-4cb7-b03c-1b4357b1f070-deployment-rubin-lee-gma-6df8b5db4b   1         1         1       4h46m
theiacloud      replicaset.apps/landing-page-deployment-798cffd84f                                          1         1         1       7h16m
theiacloud      replicaset.apps/operator-deployment-f97cd879                                                1         1         1       7h16m
theiacloud      replicaset.apps/service-deployment-548c87bbbd                                               1         1         1       7h16m

**- Rules from theia-cloud-demo-ws-ingress**

spec:
  rules:
  - host: ws.20.120.51.XXX.nip.io
  - host: ws.20.120.51.XXX.nip.io
    http:
      paths:
      - backend:
          service:
            name: a4140cf8-b66e-4610-88ce-8d5a47d773fa-service-paul-lee-nXXXXXz
            port:
              number: 3000
        path: /a4140cf8-b66e-4610-88ce-8d5a47d773fa(/|$)(.*)
        pathType: Prefix
  tls:
  - hosts:
    - ws.20.120.51.XXX.nip.io
    secretName: ws-cert-secret
status:
  loadBalancer:
    ingress:
    - ip: 20.120.51.XXX

**Comment by haminlee** [comment]
One additional question is how to add CORS configuration codes below into ingress services for service and workspace.

```
annotations:
acme.cert-manager.io/http01-edit-in-place: "true"
cert-manager.io/cluster-issuer: letsencrypt-prod
kubernetes.io/ingress.class: nginx
nginx.ingress.kubernetes.io/enable-cors: "true"
nginx.ingress.kubernetes.io/cors-allow-credentials: "true"
nginx.ingress.kubernetes.io/cors-allow-origin: "https://theia.cloud.xx.xx.xx.xx.nip.io/"
nginx.ingress.kubernetes.io/cors-allow-methods: "PUT, GET, POST, OPTIONS, DELETE"
nginx.ingress.kubernetes.io/cors-allow-headers: "Authorization,DNT,X-CustomHeader,X-LANG,Keep-Alive,User-Agent,X-Requested-With,If-Modified-Since,Cache-Control,Content-Type,X-Api-Key,X-Device-Id,Access-Control-Allow-Origin"

```
For my case, I retrieved yaml files from running ingress services by 'kubectl get ingress' and then added CORS code into yaml files. 
As the update ymal files are used to regenerate ingress service by 'apply -f', there might be some missing or unmatched configuration, I assume.

**Comment by lucas-koehler** [comment]
Unfortunately, I did not see anything suspicious in the operator logs. Could you access the URL you mentioned directly in a browser (`ws.20.120.51.130.nip.io/a4140cf8-b66e-4610-88ce-8d5a47d773fa/`) or did you also get a `503` there? I ask because if you can access it directly, then the ingress itself works but there is another issue preventing the operator from accessing it.

Regarding CORS: Usually the service should support CORS already. So far, I did not need to specify any CORS handling in the ingress. Unfortunately, I cannot help you there and would need to research this myself.

Which version of the helm chart and theia cloud itself are you using?

**Comment by haminlee** [comment]
Thanks Lucas,

The issue has been resolved after reconfiguring with new AKS with the different options.

For the test, here's the output of accessing to the workspace pod from the internal pod: 
```
wget https://ws.20.120.51.130.nip.io/1c2a2834-5b5e-4452-bceb-77e3c9a54d87/
--2023-03-22 10:44:59--  https://ws.20.120.51.130.nip.io/1c2a2834-5b5e-4452-bceb-77e3c9a54d87/
Resolving ws.20.120.51.130.nip.io (ws.20.120.51.130.nip.io)... 20.120.51.130
Connecting to ws.20.120.51.130.nip.io (ws.20.120.51.130.nip.io)|20.120.51.130|:443... connected.
HTTP request sent, awaiting response... 503 Service Temporarily Unavailable
2023-03-22 10:44:59 ERROR 503: Service Temporarily Unavailable.
```

It seems the ip address is working but there is still the same error.
So, it concluded that there might be a problem with Kubernetes.
New AKS has been reconfigured and redeployed. Now it works.
This autoscaler option doesn't work:
    --node-count 2 \
    --enable-cluster-autoscaler \

Instead, the node count has increased.

Thanks,
