### ISSUE TITLE
Operator crashes in eager start mode if monitor is not used

### ISSUE THREAD

**Issue by paulreuter** [eclipsesource/theia-cloud#192]
### Describe the bug

I tried to convert my working lazy start setup to eager start to deal with the slow startup time. However, without a defined monitor port, there is a NullPointerException.

java.lang.NullPointerException: null
	at org.eclipse.theia.cloud.operator.handler.util.TheiaCloudServiceUtil.getServiceReplacements(TheiaCloudServiceUtil.java:81) ~[operator-0.8.0-SNAPSHOT-jar-with-dependencies.jar:?]
	at org.eclipse.theia.cloud.operator.handler.impl.EagerStartAppDefinitionAddedHandler.createAndApplyService(EagerStartAppDefinitionAddedHandler.java:160) ~[operator-0.8.0-SNAPSHOT-jar-with-dependencies.jar:?]
	at org.eclipse.theia.cloud.operator.handler.impl.EagerStartAppDefinitionAddedHandler.appDefinitionAdded(EagerStartAppDefinitionAddedHandler.java:109) ~[operator-0.8.0-SNAPSHOT-jar-with-dependencies.jar:?]
	at org.eclipse.theia.cloud.operator.TheiaCloudImpl.handleAppDefnitionEvent(TheiaCloudImpl.java:153) ~[operator-0.8.0-SNAPSHOT-jar-with-dependencies.jar:?]
	at org.eclipse.theia.cloud.operator.TheiaCloudImpl.initAppDefinition(TheiaCloudImpl.java:134) ~[operator-0.8.0-SNAPSHOT-jar-with-dependencies.jar:?]
	at java.util.ArrayList.forEach(Unknown Source) ~[?:?]
	at org.eclipse.theia.cloud.operator.TheiaCloudImpl.initAppDefinitionsAndWatchForChanges(TheiaCloudImpl.java:99) [operator-0.8.0-SNAPSHOT-jar-with-dependencies.jar:?]
	at org.eclipse.theia.cloud.operator.TheiaCloudImpl.start(TheiaCloudImpl.java:90) [operator-0.8.0-SNAPSHOT-jar-with-dependencies.jar:?]
	at org.eclipse.theia.cloud.operator.Main.runMain(Main.java:51) [operator-0.8.0-SNAPSHOT-jar-with-dependencies.jar:?]
	at org.eclipse.theia.cloud.operator.Main.main(Main.java:39) [operator-0.8.0-SNAPSHOT-jar-with-dependencies.jar:?]

### Expected behavior

Operator should be able to start sessions for appdefinitions without monitor.

**Comment by lucas-koehler** [comment]
Hi @paulreuter,
thank you very much for the report.
I had a quick look in the code and there is indeed handling missing for this in `TheiaCloudServiceUtil#getServiceReplacements(String namespace, AppDefinition appDefinition, int instance)`. This method is only used for early start explaining why the same issue doesn't occur for lazy start.

> I tried to convert my working lazy start setup to eager start to deal with the slow startup time.

One thing we noticed is that slow start up times are often caused by missing application images on the node. Thus, the app docker image often needs to be pulled before the pod starts. With application images often being over 1GB, this can take some time. Maybe a temporary remedy for you could be to pre-pull images on all nodes, i.e. by using a [Kubernetes daemon set](https://kubernetes.io/docs/concepts/workloads/controllers/daemonset/).

**Comment by paulreuter** [comment]
I have added a pull request that reuses the code of the lazy start getServiceReplacements method.
#194

**Comment by paulreuter** [comment]
> One thing we noticed is that slow start up times are often caused by missing application images on the node. Thus, the app docker image often needs to be pulled before the pod starts. With application images often being over 1GB, this can take some time. Maybe a temporary remedy for you could be to pre-pull images on all nodes, i.e. by using a [Kubernetes daemon set](https://kubernetes.io/docs/concepts/workloads/controllers/daemonset/).

Many thanks for the tip, I didn't know about daemonsets. But most of the startup delay comes from the image containing a rather hefty RCP application backend, so there is not really another option.
